machine:
  node:
    version: 0.10.28
dependencies:
  pre:
    - npm install -g bower
  override:
    - npm i
    - bower i
deployment:
  production:
    branch: master
    commands:
      - EMBER_ENV=production npm run-script build
      - rsync -qaz --delete -e ssh dist/ web@162.201.123.321:/var/www/myproject
